on: [push]
name: Rebuild Website

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@master
      
      - run: pip install -r requirements.txt
          
      - name: Setup pandoc
        uses: nikeee/setup-pandoc@v1
    
      - name: Clear build directory
        run: |
          find build/* | xargs rm -rf;
          
      - name: Setup Build Directory
        run: |
          mkdir -p ./build/de ./build/en

      - name: Build
        run: python3 build.py --language de
        
      - name: Redirect english files
        run: |
          ls build/en | xargs -I {} sh -c "./redirect.py /en/{} > ./build/{}"
          
      - name: Bundle
        run: |
          tar --dereference --hard-dereference --directory build -cvf ./artifact.tar --exclude=.git --exclude=.github .
      
      - name: Add key
        env: 
          ALLINKL: ${{ secrets.AllInkl }}
        run: ssh-add - <<< "$ALLINKL"
    
      - name: Deploy
        run: |
          scp -Cr build/ ssh-w012428e@w012428e.kasserver.com:/www/htdocs/w012428e/jasc-autmatic-website/
